import ProjectDescription

let target = TargetReference.project(path: "TuistSample", target: "TuistSample")
let testTarget = TargetReference.project(path: "TuistSample", target: "TuistSampleTests")

let someScheme: Scheme = .scheme(
    name: "SomeScheme",
    buildAction: .buildAction(targets: [target]),
    testAction: .targets([.testableTarget(target: testTarget)]),
    runAction: .runAction(configuration: .debug, executable: target),
    archiveAction: .archiveAction(configuration: .release),
    analyzeAction: .analyzeAction(configuration: .release)
)

let workspace = Workspace(
    name: "TuistSampleWorkspace",
    projects: ["TuistSample"],
    schemes: [someScheme],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)

